name: Gargantua Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
    - master
env:
  WEBAPP_NAME: Gargantua
  WEBAPP_PACKAGE_PATH: WebAPI/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: WebAPI
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore ${{ env.WORKING_DIRECTORY }}
    - name: appsettings builder
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{ env.WORKING_DIRECTORY }}/appsettings.json'
      env:
        ConnectionStrings.DbConnectionString: ${{ secrets.CONNECTION_STRING }}
    - name: Build
      run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build
    - name: Publish
      run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.WEBAPP_PACKAGE_PATH }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PWD }}
        server: ${{ secrets.SFTP_SERVER }}
        remote_path: ${{ secrets.SFTP_PATH }}
        local_path: ./${{ env.WORKING_DIRECTORY }}/*
        sftp_only: true
        delete_remote_files: true
